services:
  sglang:
    command: >-
      --enable-hierarchical-cache
      --hicache-io-backend kernel
      --hicache-mem-layout page_first
      --hicache-size 100
      --hicache-write-policy write_through_selective
