services:
  sglang:
    command: >-
      --enable-hierarchical-cache
      --hicache-size 64
      --hicache-write-policy write_through
      --hicache-io-backend kernel
      --hicache-mem-layout page_first
