services:
  gemma4:
    command: >-
      --kv-offloading-size 128
      --kv-offloading-backend native
      --kv-transfer-config '{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"spec_name":"TieringOffloadingSpec","eviction_policy":"lru","offload_prompt_only":true,"secondary_tiers":[{"type":"fs","root_dir":"/kv-cache","n_read_threads":32,"n_write_threads":16}]}}'
    volumes:
    - /data/vllm-kv-cache/gemma4-26b-a4b-tiered-kv-v026:/kv-cache
  gemma4-mtp:
    command: >-
      --kv-offloading-size 128
      --kv-offloading-backend native
      --kv-transfer-config '{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"spec_name":"TieringOffloadingSpec","eviction_policy":"lru","offload_prompt_only":true,"secondary_tiers":[{"type":"fs","root_dir":"/kv-cache","n_read_threads":32,"n_write_threads":16}]}}'
    volumes:
    - /data/vllm-kv-cache/gemma4-26b-a4b-tiered-kv-v026:/kv-cache
